"""Init

Revision ID: 91b063fba750
Revises: 
Create Date: 2025-02-02 09:37:01.864548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b063fba750'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_group',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_state',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.BIGINT(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('thread_id', sa.BIGINT(), nullable=True),
    sa.Column('business_connection_id', sa.VARCHAR(), nullable=True),
    sa.Column('destiny', sa.VARCHAR(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_item',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('group_id', sa.BIGINT(), nullable=False),
    sa.Column('term', sa.VARCHAR(), nullable=False),
    sa.Column('definition', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['card_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_item')
    op.drop_table('user_state')
    op.drop_table('card_group')
    # ### end Alembic commands ###
