"""Init

Revision ID: c157a27f9244
Revises: 
Create Date: 2025-01-31 22:11:09.718745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c157a27f9244'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_group',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_state',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.BIGINT(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('thread_id', sa.BIGINT(), nullable=True),
    sa.Column('business_connection_id', sa.VARCHAR(), nullable=True),
    sa.Column('destiny', sa.VARCHAR(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('state', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_card',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('group_id', sa.BIGINT(), nullable=False),
    sa.Column('word', sa.VARCHAR(), nullable=False),
    sa.Column('transcription', sa.VARCHAR(), nullable=False),
    sa.Column('translations', sa.JSON(), nullable=False),
    sa.Column('pos', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['card_group.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_card')
    op.drop_table('user_state')
    op.drop_table('card_group')
    # ### end Alembic commands ###
